
[platformio]
default_envs = xiao_esp32s3

[env:xiao_esp32s3]
platform = espressif32 @ ^6.4.0
board = seeed_xiao_esp32s3
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time, send_on_enter
monitor_rts = 0
monitor_dtr = 0
monitor_eol = LF

board_build.partitions = partitions.csv

board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_upload.flash_size = 8MB

build_flags = 
 -DCORE_DEBUG_LEVEL=3
 
 -DUSE_WS2812B_LED=1
 
 -DCONFIG_BT_NIMBLE_NVS_PERSIST=1
 
 -DCONFIG_BT_NIMBLE_MAX_BONDS=8
 
 -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
 
 -DCONFIG_BT_NIMBLE_SM_SC=1
 
 -DCONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE=8192
 
 -DCONFIG_BT_NIMBLE_SM_BONDING=1
 
 -DCONFIG_BT_NIMBLE_ATT_PREFERRED_MTU=247
 
 -DCONFIG_BT_NIMBLE_PHY_2M=0
 
 -DCONFIG_BT_NIMBLE_DEBUG=0
 
 -DCONFIG_ESP_TASK_WDT=1
 -DCONFIG_ESP_TASK_WDT_TIMEOUT_S=30
 
 -Os
 
 -DARDUINO_LOOP_STACK_SIZE=16384
 
 -DFIRMWARE_VERSION_MAJOR=2
 -DFIRMWARE_VERSION_MINOR=5
 -DFIRMWARE_VERSION_PATCH=0
 -DFIRMWARE_BUILD_TYPE=0
 '-DFIRMWARE_BUILD_DATE="${BUILD_DATE}"'

 -DARDUINO_USB_CDC_ON_BOOT=1
 -DARDUINO_USB_MODE=1
 
 -DCONFIG_PM_ENABLE=1

lib_deps = 
 h2zero/NimBLE-Arduino @ ^1.4.1
 
 fastled/FastLED @ ^3.6.0
 
upload_speed = 921600
upload_protocol = esptool

[env:xiao_esp32s3_debug]
extends = env:xiao_esp32s3

build_flags = 
 ${env:xiao_esp32s3.build_flags}
 -DCORE_DEBUG_LEVEL=5
 -DCONFIG_BT_NIMBLE_DEBUG=1
 -DDEBUG_MODE=1

[env:xiao_esp32s3_release]
extends = env:xiao_esp32s3

build_flags = 
 ${env:xiao_esp32s3.build_flags}
 -DCORE_DEBUG_LEVEL=1
 -DNDEBUG
 -O2

build_unflags = -Os

[env:xiao_esp32s3_dist]
extends = env:xiao_esp32s3
build_flags =
 -DUSE_WS2812B_LED=1

 -DCONFIG_BT_NIMBLE_NVS_PERSIST=1
 -DCONFIG_BT_NIMBLE_MAX_BONDS=8
 -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
 -DCONFIG_BT_NIMBLE_SM_SC=1
 -DCONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE=8192
 -DCONFIG_BT_NIMBLE_SM_BONDING=1
 -DCONFIG_BT_NIMBLE_ATT_PREFERRED_MTU=247
 -DCONFIG_BT_NIMBLE_PHY_2M=0
 -DCONFIG_BT_NIMBLE_DEBUG=0

 -DCONFIG_ESP_TASK_WDT=1
 -DCONFIG_ESP_TASK_WDT_TIMEOUT_S=30
 -DARDUINO_LOOP_STACK_SIZE=16384
 -DCONFIG_PM_ENABLE=1

 -DFIRMWARE_VERSION_MAJOR=2
 -DFIRMWARE_VERSION_MINOR=5
 -DFIRMWARE_VERSION_PATCH=0
 -DFIRMWARE_BUILD_TYPE=0
 '-DFIRMWARE_BUILD_DATE="${BUILD_DATE}"'

 -DCORE_DEBUG_LEVEL=0

 -DCONFIG_LOG_DEFAULT_LEVEL=0
 -DCONFIG_LOG_MAXIMUM_LEVEL=0

 -DARDUINO_USB_CDC_ON_BOOT=0
 -DARDUINO_USB_MODE=0

 -DDIST_BUILD=1

 -DNDEBUG

 -Os

 -ffile-prefix-map=${PROJECT_DIR}=.
 -ffile-prefix-map=/home=~

build_unflags =
 -DARDUINO_USB_CDC_ON_BOOT=1
 -DARDUINO_USB_MODE=1