
#ifndef NIMCONFIG_H
#define NIMCONFIG_H


#define CONFIG_BT_NIMBLE_NVS_PERSIST 1

#define CONFIG_BT_NIMBLE_MAX_BONDS 8

#define CONFIG_BT_NIMBLE_SM_SC 1

#define CONFIG_BT_NIMBLE_SM_BONDING 1


#define CONFIG_BT_NIMBLE_MAX_CONNECTIONS 1

#define CONFIG_BT_NIMBLE_MAX_CCCDS 8

#define CONFIG_BT_NIMBLE_ATT_PREFERRED_MTU 247


#define CONFIG_BT_NIMBLE_PHY_2M 0


#define CONFIG_BT_NIMBLE_ATT_VALUE_MAX 256

#define CONFIG_BT_NIMBLE_MAX_ATTRIBUTES 25


#ifndef CONFIG_BT_NIMBLE_DEBUG
#define CONFIG_BT_NIMBLE_DEBUG 0
#endif


#define CONFIG_BT_NIMBLE_ADV_DATA_MAX_LEN 31


#ifndef CONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED
#define CONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED 1
#endif

#ifndef CONFIG_BT_NIMBLE_ROLE_BROADCASTER_DISABLED
#define CONFIG_BT_NIMBLE_ROLE_BROADCASTER_DISABLED 1
#endif

#ifdef CONFIG_BT_NIMBLE_ROLE_PERIPHERAL
#undef CONFIG_BT_NIMBLE_ROLE_PERIPHERAL
#endif
#define CONFIG_BT_NIMBLE_ROLE_PERIPHERAL 1


#if !defined(CONFIG_BT_NIMBLE_NVS_PERSIST) || CONFIG_BT_NIMBLE_NVS_PERSIST == 0
#error "CONFIG_BT_NIMBLE_NVS_PERSIST must be 1 for iOS bonding support"
#endif

#if CONFIG_BT_NIMBLE_MAX_BONDS < 1
#error "CONFIG_BT_NIMBLE_MAX_BONDS must be at least 1"
#endif

#if !defined(CONFIG_BT_NIMBLE_SM_SC) || CONFIG_BT_NIMBLE_SM_SC == 0
#error "CONFIG_BT_NIMBLE_SM_SC must be 1 for iOS 10+ compatibility"
#endif

#endif

